platform :ios,’8.0’
target 'ZPJawaMall' do
    pod 'AFNetworking'
    pod ’SDWebImage’
    pod 'BeeCloud'
    pod 'BeeCloud/Alipay'
    pod 'BeeCloud/Wx'
    pod 'BeeCloud/UnionPay'
    pod 'BeeCloud/PayPal'
    pod 'BeeCloud/Baidu'
    pod 'BeeCloud/ApplePay'
    pod 'MBProgressHUD', '~> 1.0.0'
end
